# Generated by Django 5.0.7 on 2025-05-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.ManyToManyField(to='base.day'),
        ),
    ]
