# Generated by Django 5.0.7 on 2025-06-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_day_remove_course_day_of_week_course_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course/images'),
        ),
    ]
