# Generated by Django 5.0.7 on 2025-06-09 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_image/'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('student', 'course')},
        ),
    ]
